<a href="https://colab.research.google.com/github/Spoorti803/AI_Powered_Intrusion_Detection_System_Using_Network_Traffic_Flow/blob/main/PreprocessingCICIDS2017.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 'Kaagaz_20220914_141308009993.pdf',
 'Kaagaz_20220914_141308009993.gdoc',
 'Untitled presentation (4).gslides',
 'Untitled presentation (3).gslides',
 'Untitled presentation (2).gslides',
 'Untitled presentation (1).gslides',
 'Untitled presentation.gslides',
 'Untitled form (1).gform',
 'Untitled form.gform',
 'AmazonLogo.jpg',
 'SignIn.jpg',
 'E-Commerce.html',
 'SignUp.html',
 'SignIn.html',
 'Forgot.html',
 'Successful.html',
 'style (1).css',
 'StripLight.jpg',
 'hero-img.jpg',
 'style2.css',
 'Laptop.jpg',
 'Smartwatch.jpg',
 'RoomFreshner.jpg',
 'signup.html',
 'signin.html',
 'forgot.html',
 'twoa.html',
 'styletwo.css',
 'style.css',
 'successfull.html',
 'AmazonImage.jpg',
 'ScrollinBlinking.html',
 "Vaibhavi's Resume.pdf",
 "Vaibhavi's Resume (1).gdoc",
 "Vaibhavi's Resume.gdoc",
 'nnm22cs195.pdf',
 'Vaibhavi N-Resume (3).pdf',
 'Sambhram Permission.gdoc',
 'Vaibhavi N-Resume (1).pdf',
 'Vaibhavi N-Resume.pdf',
 'Classroom',
 'archive (8)',
 'Patent APPLICATION FORM.docx',
 'Final_Year_Project (1).gdoc',
 'Vaibhavi N-Resume (2).pdf',
 'Vaibhavi N-Resume (2)-1.pdf',
 'Photoshoot 25',
 'Intern Information Form.docx',
 '36101.jpg',
 'Miniproject_MSIS_papers.docx',
 'bestsellers with categories.csv',
 'Data.csv',
 'Groceries_dataset.csv',
 'Copy of bestsellers with categories.csv',
 'Iris.csv',
 'diabetes.csv',
 'Social_Network_Ads.csv',
 'adult.csv',
 'Salary_Data.csv',
 'Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
 'Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
 'Friday-WorkingHours-Morning.pcap_ISCX.csv',
 'Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv',
 'Monday-WorkingHours.pcap_ISCX.csv',
 'Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
 'Tuesday-WorkingHours.pcap_ISCX.csv',
 'Wednesday-workingHours.pcap_ISCX.csv']

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
# Loading the dataset
data1 = pd.read_csv('/content/drive/MyDrive/Monday-WorkingHours.pcap_ISCX.csv')
data2 = pd.read_csv('/content/drive/MyDrive/Tuesday-WorkingHours.pcap_ISCX.csv')
data3 = pd.read_csv('/content/drive/MyDrive/Wednesday-workingHours.pcap_ISCX.csv')
data4 = pd.read_csv('/content/drive/MyDrive/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv')
data5 = pd.read_csv('/content/drive/MyDrive/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv')
data6 = pd.read_csv('/content/drive/MyDrive/Friday-WorkingHours-Morning.pcap_ISCX.csv')
data7 = pd.read_csv('/content/drive/MyDrive/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv')
data8 = pd.read_csv('/content/drive/MyDrive/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv')

In [7]:
data1.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,49188,4,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,49486,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [8]:
data1.shape

(529918, 79)

In [9]:
data1.dtypes

 Destination Port                int64
 Flow Duration                   int64
 Total Fwd Packets               int64
 Total Backward Packets          int64
Total Length of Fwd Packets      int64
                                ...
Idle Mean                      float64
 Idle Std                      float64
 Idle Max                        int64
 Idle Min                        int64
 Label                          object
Length: 79, dtype: object

In [10]:
data1.describe()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,529918.000000,5.299180e+05,529918.000000,529918.000000,5.299180e+05,5.299180e+05,529918.000000,529918.000000,529918.000000,529918.000000,...,529918.000000,5.299180e+05,5.299180e+05,5.299180e+05,5.299180e+05,5.299180e+05,5.299180e+05,5.299180e+05,5.299180e+05,5.299180e+05
mean,10644.367112,1.038927e+07,10.390315,11.517105,5.324195e+02,1.789841e+04,190.897188,20.277279,50.744078,57.452269,...,7.412509,-3.614576e+03,6.843482e+04,4.321930e+04,1.453907e+05,4.380369e+04,3.463918e+06,2.024408e+05,3.620657e+06,3.274066e+06
std,21390.213475,2.875195e+07,892.412791,1173.318788,6.228642e+03,2.675470e+06,448.833754,36.275793,91.964713,146.518081,...,851.762351,5.526328e+05,5.872322e+05,3.971455e+05,1.028606e+06,4.993677e+05,1.297057e+07,2.170149e+06,1.340649e+07,1.273216e+07
min,0.000000,-1.000000e+00,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,-8.388531e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,53.000000,1.760000e+02,2.000000,1.000000,1.800000e+01,0.000000e+00,6.000000,0.000000,6.000000,0.000000,...,0.000000,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,80.000000,3.130300e+04,2.000000,2.000000,6.800000e+01,1.440000e+02,40.000000,6.000000,38.000000,0.000000,...,1.000000,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,443.000000,3.557448e+05,4.000000,3.000000,1.870000e+02,3.920000e+02,83.000000,40.000000,53.000000,26.162951,...,3.000000,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,65535.000000,1.200000e+08,219759.000000,291922.000000,1.323378e+06,6.554530e+08,23360.000000,2293.000000,4638.923469,7125.596846,...,213557.000000,1.260000e+02,1.016597e+08,6.434950e+07,1.016597e+08,1.016597e+08,1.199997e+08,7.514502e+07,1.199997e+08,1.199997e+08

In [11]:

data_list = [data1, data2, data3, data4, data5, data6, data7, data8]

print('Data dimensions: ')
for i, data in enumerate(data_list, start = 1):
  rows, cols = data.shape
  print(f'Data{i} -> {rows} rows, {cols} columns')

Data dimensions:
Data1 -> 529918 rows, 79 columns
Data2 -> 445909 rows, 79 columns
Data3 -> 692703 rows, 79 columns
Data4 -> 170366 rows, 79 columns
Data5 -> 288602 rows, 79 columns
Data6 -> 191033 rows, 79 columns
Data7 -> 286467 rows, 79 columns
Data8 -> 225745 rows, 79 columns

In [12]:

data = pd.concat(data_list)
rows, cols = data.shape

print('New dimension:')
print(f'Number of rows: {rows}')
print(f'Number of columns: {cols}')
print(f'Total cells: {rows * cols}')

New dimension:
Number of rows: 2830743
Number of columns: 79
Total cells: 223628697

In [13]:

# Deleting dataframes after concating to save memory
for d in data_list: del d

In [14]:
# Renaming the columns by removing leading/trailing whitespace
col_names = {col: col.strip() for col in data.columns}
data.rename(columns = col_names, inplace = True)

In [15]:
data.columns

Index(['Destination Port', 'Flow Duration', 'Total Fwd Packets',
       'Total Backward Packets', 'Total Length of Fwd Packets',
       'Total Length of Bwd Packets', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std', 'Bwd Packet Length Max',
       'Bwd Packet Length Min', 'Bwd Packet Length Mean',
       'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
       'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
       'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max',
       'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
       'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags',
       'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Min Packet Length', 'Max Packet Length', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
       'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk',
       'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes',
       'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
       'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean',
       'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2830743 entries, 0 to 225744
Data columns (total 79 columns):
 #   Column                       Dtype
---  ------                       -----
 0   Destination Port             int64
 1   Flow Duration                int64
 2   Total Fwd Packets            int64
 3   Total Backward Packets       int64
 4   Total Length of Fwd Packets  int64
 5   Total Length of Bwd Packets  int64
 6   Fwd Packet Length Max        int64
 7   Fwd Packet Length Min        int64
 8   Fwd Packet Length Mean       float64
 9   Fwd Packet Length Std        float64
 10  Bwd Packet Length Max        int64
 11  Bwd Packet Length Min        int64
 12  Bwd Packet Length Mean       float64
 13  Bwd Packet Length Std        float64
 14  Flow Bytes/s                 float64
 15  Flow Packets/s               float64
 16  Flow IAT Mean                float64
 17  Flow IAT Std                 float64
 18  Flow IAT Max                 int64
 19  Flow IAT Min                 int64
 20  Fwd IAT Total                int64
 21  Fwd IAT Mean                 float64
 22  Fwd IAT Std                  float64
 23  Fwd IAT Max                  int64
 24  Fwd IAT Min                  int64
 25  Bwd IAT Total                int64
 26  Bwd IAT Mean                 float64
 27  Bwd IAT Std                  float64
 28  Bwd IAT Max                  int64
 29  Bwd IAT Min                  int64
 30  Fwd PSH Flags                int64
 31  Bwd PSH Flags                int64
 32  Fwd URG Flags                int64
 33  Bwd URG Flags                int64
 34  Fwd Header Length            int64
 35  Bwd Header Length            int64
 36  Fwd Packets/s                float64
 37  Bwd Packets/s                float64
 38  Min Packet Length            int64
 39  Max Packet Length            int64
 40  Packet Length Mean           float64
 41  Packet Length Std            float64
 42  Packet Length Variance       float64
 43  FIN Flag Count               int64
 44  SYN Flag Count               int64
 45  RST Flag Count               int64
 46  PSH Flag Count               int64
 47  ACK Flag Count               int64
 48  URG Flag Count               int64
 49  CWE Flag Count               int64
 50  ECE Flag Count               int64
 51  Down/Up Ratio                int64
 52  Average Packet Size          float64
 53  Avg Fwd Segment Size         float64
 54  Avg Bwd Segment Size         float64
 55  Fwd Header Length.1          int64
 56  Fwd Avg Bytes/Bulk           int64
 57  Fwd Avg Packets/Bulk         int64
 58  Fwd Avg Bulk Rate            int64
 59  Bwd Avg Bytes/Bulk           int64
 60  Bwd Avg Packets/Bulk         int64
 61  Bwd Avg Bulk Rate            int64
 62  Subflow Fwd Packets          int64
 63  Subflow Fwd Bytes            int64
 64  Subflow Bwd Packets          int64
 65  Subflow Bwd Bytes            int64
 66  Init_Win_bytes_forward       int64
 67  Init_Win_bytes_backward      int64
 68  act_data_pkt_fwd             int64
 69  min_seg_size_forward         int64
 70  Active Mean                  float64
 71  Active Std                   float64
 72  Active Max                   int64
 73  Active Min                   int64
 74  Idle Mean                    float64
 75  Idle Std                     float64
 76  Idle Max                     int64
 77  Idle Min                     int64
 78  Label                        object
dtypes: float64(24), int64(54), object(1)
memory usage: 1.7+ GB

In [20]:
pd.options.display.max_rows = 80
print('Overview of Columns:')
data.describe().transpose()

Overview of Columns:

,count,mean,std,min,25%,50%,75%,max
Destination Port,2830743.0,8.071483e+03,1.828363e+04,0.000000e+00,53.000000,80.000000,4.430000e+02,6.553500e+04
Flow Duration,2830743.0,1.478566e+07,3.365374e+07,-1.300000e+01,155.000000,31316.000000,3.204828e+06,1.200000e+08
Total Fwd Packets,2830743.0,9.361160e+00,7.496728e+02,1.000000e+00,2.000000,2.000000,5.000000e+00,2.197590e+05
Total Backward Packets,2830743.0,1.039377e+01,9.973883e+02,0.000000e+00,1.000000,2.000000,4.000000e+00,2.919220e+05
Total Length of Fwd Packets,2830743.0,5.493024e+02,9.993589e+03,0.000000e+00,12.000000,62.000000,1.870000e+02,1.290000e+07
Total Length of Bwd Packets,2830743.0,1.616264e+04,2.263088e+06,0.000000e+00,0.000000,123.000000,4.820000e+02,6.554530e+08
Fwd Packet Length Max,2830743.0,2.075999e+02,7.171848e+02,0.000000e+00,6.000000,37.000000,8.100000e+01,2.482000e+04
Fwd Packet Length Min,2830743.0,1.871366e+01,6.033935e+01,0.000000e+00,0.000000,2.000000,3.600000e+01,2.325000e+03
Fwd Packet Length Mean,2830743.0,5.820194e+01,1.860912e+02,0.000000e+00,6.000000,34.000000,5.000000e+01,5.940857e+03
Fwd Packet Length Std,2830743.0,6.891013e+01,2.811871e+02,0.000000e+00,0.000000,0.000000,2.616295e+01,7.125597e+03
Bwd Packet Length Max,2830743.0,8.708495e+02,1.946367e+03,0.000000e+00,0.000000,79.000000,2.800000e+02,1.953000e+04
Bwd Packet Length Min,2830743.0,4.104958e+01,6.886260e+01,0.000000e+00,0.000000,0.000000,7.700000e+01,2.896000e+03
Bwd Packet Length Mean,2830743.0,3.059493e+02,6.052568e+02,0.000000e+00,0.000000,72.000000,1.810000e+02,5.800500e+03
Bwd Packet Length Std,2830743.0,3.353257e+02,8.396932e+02,0.000000e+00,0.000000,0.000000,7.794054e+01,8.194660e+03
Flow Bytes/s,2829385.0,inf,NaN,-2.610000e+08,119.319731,4595.549126,1.666667e+05,inf
Flow Packets/s,2830743.0,inf,NaN,-2.000000e+06,3.446226,110.668437,2.325581e+04,inf
Flow IAT Mean,2830743.0,1.298449e+06,4.507944e+06,-1.300000e+01,63.666667,11438.842110,3.374266e+05,1.200000e+08
Flow IAT Std,2830743.0,2.919271e+06,8.045870e+06,0.000000e+00,0.000000,137.178716,6.912663e+05,8.480026e+07
Flow IAT Max,2830743.0,9.182475e+06,2.445954e+07,-1.300000e+01,123.000000,30865.000000,2.440145e+06,1.200000e+08
Flow IAT Min,2830743.0,1.623796e+05,2.950282e+06,-1.400000e+01,3.000000,4.000000,6.400000e+01,1.200000e+08
Fwd IAT Total,2830743.0,1.448296e+07,3.357581e+07,0.000000e+00,0.000000,43.000000,1.242844e+06,1.200000e+08
Fwd IAT Mean,2830743.0,2.610193e+06,9.525722e+06,0.000000e+00,0.000000,26.000000,2.063064e+05,1.200000e+08
Fwd IAT Std,2830743.0,3.266957e+06,9.639055e+06,0.000000e+00,0.000000,0.000000,6.598982e+04,8.460293e+07
Fwd IAT Max,2830743.0,9.042939e+06,2.452916e+07,0.000000e+00,0.000000,43.000000,9.310060e+05,1.200000e+08
Fwd IAT Min,2830743.0,1.021893e+06,8.591436e+06,-1.200000e+01,0.000000,3.000000,4.800000e+01,1.200000e+08
Bwd IAT Total,2830743.0,9.893830e+06,2.873661e+07,0.000000e+00,0.000000,3.000000,9.858050e+04,1.200000e+08
Bwd IAT Mean,2830743.0,1.805784e+06,8.887197e+06,0.000000e+00,0.000000,3.000000,1.824857e+04,1.200000e+08
Bwd IAT Std,2830743.0,1.485973e+06,6.278469e+06,0.000000e+00,0.000000,0.000000,1.572409e+04,8.441801e+07
Bwd IAT Max,2830743.0,4.684692e+06,1.716095e+07,0.000000e+00,0.000000,3.000000,6.021000e+04,1.200000e+08
Bwd IAT Min,2830743.0,9.672614e+05,8.308983e+06,0.000000e+00,0.000000,1.000000,4.500000e+01,1.200000e+08
Fwd PSH Flags,2830743.0,4.644646e-02,2.104500e-01,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
Bwd PSH Flags,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Fwd URG Flags,2830743.0,1.112782e-04,1.054826e-02,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
Bwd URG Flags,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Fwd Header Length,2830743.0,-2.599739e+04,2.105286e+07,-3.221223e+10,40.000000,64.000000,1.200000e+02,4.644908e+06
Bwd Header Length,2830743.0,-2.273275e+03,1.452209e+06,-1.073741e+09,20.000000,40.000000,1.040000e+02,5.838440e+06
Fwd Packets/s,2830743.0,6.386535e+04,2.475371e+05,0.000000e+00,1.749446,61.325238,1.204819e+04,3.000000e+06
Bwd Packets/s,2830743.0,6.995192e+03,3.815170e+04,0.000000e+00,0.122920,19.827894,7.352941e+03,2.000000e+06
Min Packet Length,2830743.0,1.643450e+01,2.523772e+01,0.000000e+00,0.000000,2.000000,3.600000e+01,1.448000e+03
Max Packet Length,2830743.0,9.504024e+02,2.028229e+03,0.000000e+00,6.000000,87.000000,5.250000e+02,2.482000e+04
Packet Length Mean,2830743.0,1.719444e+02,3.054915e+02,0.000000e+00,6.000000,57.200000,1.198000e+02,3.337143e+03
Packet Length Std,2830743.0,2.949756e+02,6.318001e+02,0.000000e+00,0.000000,25.980762,1.743239e+02,4.731522e+03
Packet Length Variance,2830743.0,4.861548e+05,1.647490e+06,0.000000e+00,0.000000,675.000000,3.038884e+04,2.240000e+07
FIN Flag Count,2830743.0,3.537976e-02,1.847378e-01,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
SYN Flag Count,2830743.0,4.644646e-02,2.104500e-01,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
RST Flag Count,2830743.0,2.423392e-04,1.556536e-02,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
PSH Flag Count,2830743.0,2.980705e-01,4.574107e-01,0.000000e+00,0.000000,0.000000,1.000000e+00,1.000000e+00
ACK Flag Count,2830743.0,3.158443e-01,4.648513e-01,0.000000e+00,0.000000,0.000000,1.000000e+00,1.000000e+00
URG Flag Count,2830743.0,9.482316e-02,2.929706e-01,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
CWE Flag Count,2830743.0,1.112782e-04,1.054826e-02,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
ECE Flag Count,2830743.0,2.433990e-04,1.559935e-02,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
Down/Up Ratio,2830743.0,6.835004e-01,6.804920e-01,0.000000e+00,0.000000,1.000000,1.000000e+00,1.560000e+02
Average Packet Size,2830743.0,1.919837e+02,3.318603e+02,0.000000e+00,7.500000,72.250000,1.492639e+02,3.893333e+03
Avg Fwd Segment Size,2830743.0,5.820194e+01,1.860912e+02,0.000000e+00,6.000000,34.000000,5.000000e+01,5.940857e+03
Avg Bwd Segment Size,2830743.0,3.059493e+02,6.052568e+02,0.000000e+00,0.000000,72.000000,1.810000e+02,5.800500e+03
Fwd Header Length.1,2830743.0,-2.599739e+04,2.105286e+07,-3.221223e+10,40.000000,64.000000,1.200000e+02,4.644908e+06
Fwd Avg Bytes/Bulk,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Fwd Avg Packets/Bulk,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Fwd Avg Bulk Rate,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Bwd Avg Bytes/Bulk,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Bwd Avg Packets/Bulk,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Bwd Avg Bulk Rate,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Subflow Fwd Packets,2830743.0,9.361160e+00,7.496728e+02,1.000000e+00,2.000000,2.000000,5.000000e+00,2.197590e+05
Subflow Fwd Bytes,2830743.0,5.492919e+02,9.980070e+03,0.000000e+00,12.000000,62.000000,1.870000e+02,1.287034e+07
Subflow Bwd Packets,2830743.0,1.039377e+01,9.973883e+02,0.000000e+00,1.000000,2.000000,4.000000e+00,2.919220e+05
Subflow Bwd Bytes,2830743.0,1.616230e+04,2.263057e+06,0.000000e+00,0.000000,123.000000,4.820000e+02,6.554530e+08
Init_Win_bytes_forward,2830743.0,6.989837e+03,1.433873e+04,-1.000000e+00,-1.000000,251.000000,8.192000e+03,6.553500e+04
Init_Win_bytes_backward,2830743.0,1.989433e+03,8.456883e+03,-1.000000e+00,-1.000000,-1.000000,2.350000e+02,6.553500e+04
act_data_pkt_fwd,2830743.0,5.418218e+00,6.364257e+02,0.000000e+00,0.000000,1.000000,2.000000e+00,2.135570e+05
min_seg_size_forward,2830743.0,-2.741688e+03,1.084989e+06,-5.368707e+08,20.000000,24.000000,3.200000e+01,1.380000e+02
Active Mean,2830743.0,8.155132e+04,6.485999e+05,0.000000e+00,0.000000,0.000000,0.000000e+00,1.100000e+08
Active Std,2830743.0,4.113412e+04,3.933815e+05,0.000000e+00,0.000000,0.000000,0.000000e+00,7.420000e+07
Active Max,2830743.0,1.531825e+05,1.025825e+06,0.000000e+00,0.000000,0.000000,0.000000e+00,1.100000e+08
Active Min,2830743.0,5.829582e+04,5.770923e+05,0.000000e+00,0.000000,0.000000,0.000000e+00,1.100000e+08
Idle Mean,2830743.0,8.316037e+06,2.363008e+07,0.000000e+00,0.000000,0.000000,0.000000e+00,1.200000e+08
Idle Std,2830743.0,5.038439e+05,4.602984e+06,0.000000e+00,0.000000,0.000000,0.000000e+00,7.690000e+07
Idle Max,2830743.0,8.695752e+06,2.436689e+07,0.000000e+00,0.000000,0.000000,0.000000e+00,1.200000e+08
Idle Min,2830743.0,7.920031e+06,2.336342e+07,0.000000e+00,0.000000,0.000000,0.000000e+00,1.200000e+08

In [21]:
pd.options.display.max_columns = 80
data

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,49188,4,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,3.000000e+06,5.000000e+05,4.0,0.0,4,4,4,4.0,0.0,4,4,0,0.0,0.0,0,0,0,0,0,0,40,0,5.000000e+05,0.00000,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,329,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,49188,1,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,1.200000e+07,2.000000e+06,1.0,0.0,1,1,1,1.0,0.0,1,1,0,0.0,0.0,0,0,0,0,0,0,40,0,2.000000e+06,0.00000,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,329,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,49188,1,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,1.200000e+07,2.000000e+06,1.0,0.0,1,1,1,1.0,0.0,1,1,0,0.0,0.0,0,0,0,0,0,0,40,0,2.000000e+06,0.00000,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,329,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,49188,1,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,1.200000e+07,2.000000e+06,1.0,0.0,1,1,1,1.0,0.0,1,1,0,0.0,0.0,0,0,0,0,0,0,40,0,2.000000e+06,0.00000,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,329,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,49486,3,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,4.000000e+06,6.666667e+05,3.0,0.0,3,3,3,3.0,0.0,3,3,0,0.0,0.0,0,0,0,0,0,0,40,0,6.666667e+05,0.00000,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,245,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225740,61374,61,1,1,6,6,6,6,6.0,0.0,6,6,6.0,0.0,1.967213e+05,3.278689e+04,61.0,0.0,61,61,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,20,20,1.639344e+04,16393.44262,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,1,9.0,6.0,6.0,20,0,0,0,0,0,0,1,6,1,6,288,253,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225741,61378,72,1,1,6,6,6,6,6.0,0.0,6,6,6.0,0.0,1.666667e+05,2.777778e+04,72.0,0.0,72,72,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,20,20,1.388889e+04,13888.88889,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,1,9.0,6.0,6.0,20,0,0,0,0,0,0,1,6,1,6,288,253,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225742,61375,75,1,1,6,6,6,6,6.0,0.0,6,6,6.0,0.0,1.600000e+05,2.666667e+04,75.0,0.0,75,75,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,20,20,1.333333e+04,13333.33333,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,1,9.0,6.0,6.0,20,0,0,0,0,0,0,1,6,1,6,288,253,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225743,61323,48,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,2.500000e+05,4.166667e+04,48.0,0.0,48,48,48,48.0,0.0,48,48,0,0.0,0.0,0,0,0,0,0,0,40,0,4.166667e+04,0.00000,6,6,6.0,0.0,0.0,0,0,0,0,1,0,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,4719,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225744,61326,68,1,1,6,6,6,6,6.0,0.0,6,6,6.0,0.0,1.764706e+05,2.941176e+04,68.0,0.0,68,68,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,20,20,1.470588e+04,14705.88235,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,1,9.0,6.0,6.0,20,0,0,0,0,0,0,1,6,1,6,13140,64240,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN